# Simple Examples

In [3]:
from OSMPythonTools.nominatim import Nominatim
nominatim = Nominatim()
areaId = nominatim.query('Vienna, Austria').areaId()
print(f'areaId : {areaId}')
# This area id can now be used to build the corresponding query:

areaId : 3600109166

In [4]:
from OSMPythonTools.overpass import overpassQueryBuilder, Overpass
overpass = Overpass()
query = overpassQueryBuilder(area=areaId, elementType='node', selector='"amenity"="school"', out='count')
result = overpass.query(query)
result.countElements()
# 137830

188

# Städte in Deutschland


https://de.wikipedia.org/wiki/Liste_der_Gro%C3%9Fst%C3%A4dte_in_Deutschland

# Get List of Towns

In [37]:
import pandas as pd

def getTowns():
    # Start : Global configuration
    # Get Table
    url = "https://de.wikipedia.org/wiki/Liste_der_Gro%C3%9Fst%C3%A4dte_in_Deutschland"
    tables = pd.read_html(url,decimal=',', thousands='.')
    
    grossstadte = tables[0] 
    
    return grossstadte

In [38]:
townsTable = getTowns()[:-2]
townsTable

   Rang(2020)               Name  \
   Rang(2020)               Name
0           1            Berlin1
1           2           Hamburg1
2           3            München
3           4              Köln1
4           5  Frankfurt am Main
..        ...                ...
75         76    Salzgitter1, 11
76         77             Moers1
77         78            Siegen1
78         79        Hildesheim1
79         80          Gütersloh

                                        Einwohnerzahl                    \
                                              1939[2]     1950     1960
0   .mw-parser-output .numericFormat-1000::after{c...  3336026  3274016
1                                             1698388  1605606  1836958
2                                              815212   831937  1101384
3                                              768352   594941   801142
4                                              548220   532037   675009
..                                                ...      ...      ...
75                                              45598   100667   108872
76                                              29646    34832    45908
77                                              37622    38787    48210
78                                              68679    72292    94352
79                                              32841    43111    52346

                                                                   \
       1970     1980     1990     2000     2010     2019     2020
0   3208719  3048759  3433695  3382169  3460725  3669491  3664088
1   1793640  1645095  1652363  1715392  1786448  1847253  1852478
2   1311978  1298941  1229026  1210223  1353186  1484226  1488202
3    849451   976694   953551   962884  1007119  1087863  1083498
4    666179   629375   644865   648550   679664   763380   764104
..      ...      ...      ...      ...      ...      ...      ...
75   119031   113600   114355   112302   102394   104291   103866
76    53410    99923   104595   107062   105506   103902   103487
77    57563   112320   109174   108476   103424   102770   101943
78    93373   102619   105291   103909   102794   101693   101055
79    75297    78221    86807    95156    96404   100861   100664

   Fläche in km² (2016) Ew./km² (2018)  \
   Fläche in km² (2016) Ew./km² (2018)
0                891.68           4088
1                755.22           2438
2                310.70           4736
3                405.02           2681
4                248.31           3033
..                  ...            ...
75               223.92            469
76                67.68           1533
77               114.69            897
78                92.18           1106
79               112.02            894

   Be­völ­ke­rungs-ent­wick­lung [%] (2020 ggü. 2019) Großstadt erst­mals1  \
   Be­völ­ke­rungs-ent­wick­lung [%] (2020 ggü. 2019) Großstadt erst­mals1
0                                               -0.15                 1747
1                                                0.28                 1787
2                                                0.27                 1852
3                                               -0.40                 1852
4                                                0.09                 1875
..                                                ...                  ...
75                                              -0.41                 1942
76                                              -0.40                 1975
77                                              -0.80                 1975
78                                              -0.63                 1974
79                                              -0.20                 2018

           Bun­des­land
           Bun­des­land
0                Berlin
1               Hamburg
2                Bayern
3   Nordrhein-Westfalen
4                Hessen
..                  ...
75        Niedersachsen
76  Nordrhein-Westfalen
77  Nordrhein-Westfalen
78        Niedersachsen
79  Nordrhein-Westfalen

[80 rows x 17 columns]

# Clean Town names

In [40]:
import re

townsTable.loc[:,('Name','Name')] = townsTable.loc[:,('Name','Name')]. \
    apply(lambda x: re.sub(r'[0-9]', '', x)). \
    apply(lambda x:  x.replace('(Oldb)','') ). \
    apply(lambda x: re.sub(r',', '', x)) # removeCommas
townsTable

   Rang(2020)               Name  \
   Rang(2020)               Name
0           1             Berlin
1           2            Hamburg
2           3            München
3           4               Köln
4           5  Frankfurt am Main
..        ...                ...
75         76        Salzgitter
76         77              Moers
77         78             Siegen
78         79         Hildesheim
79         80          Gütersloh

                                        Einwohnerzahl                    \
                                              1939[2]     1950     1960
0   .mw-parser-output .numericFormat-1000::after{c...  3336026  3274016
1                                             1698388  1605606  1836958
2                                              815212   831937  1101384
3                                              768352   594941   801142
4                                              548220   532037   675009
..                                                ...      ...      ...
75                                              45598   100667   108872
76                                              29646    34832    45908
77                                              37622    38787    48210
78                                              68679    72292    94352
79                                              32841    43111    52346

                                                                   \
       1970     1980     1990     2000     2010     2019     2020
0   3208719  3048759  3433695  3382169  3460725  3669491  3664088
1   1793640  1645095  1652363  1715392  1786448  1847253  1852478
2   1311978  1298941  1229026  1210223  1353186  1484226  1488202
3    849451   976694   953551   962884  1007119  1087863  1083498
4    666179   629375   644865   648550   679664   763380   764104
..      ...      ...      ...      ...      ...      ...      ...
75   119031   113600   114355   112302   102394   104291   103866
76    53410    99923   104595   107062   105506   103902   103487
77    57563   112320   109174   108476   103424   102770   101943
78    93373   102619   105291   103909   102794   101693   101055
79    75297    78221    86807    95156    96404   100861   100664

   Fläche in km² (2016) Ew./km² (2018)  \
   Fläche in km² (2016) Ew./km² (2018)
0                891.68           4088
1                755.22           2438
2                310.70           4736
3                405.02           2681
4                248.31           3033
..                  ...            ...
75               223.92            469
76                67.68           1533
77               114.69            897
78                92.18           1106
79               112.02            894

   Be­völ­ke­rungs-ent­wick­lung [%] (2020 ggü. 2019) Großstadt erst­mals1  \
   Be­völ­ke­rungs-ent­wick­lung [%] (2020 ggü. 2019) Großstadt erst­mals1
0                                               -0.15                 1747
1                                                0.28                 1787
2                                                0.27                 1852
3                                               -0.40                 1852
4                                                0.09                 1875
..                                                ...                  ...
75                                              -0.41                 1942
76                                              -0.40                 1975
77                                              -0.80                 1975
78                                              -0.63                 1974
79                                              -0.20                 2018

           Bun­des­land
           Bun­des­land
0                Berlin
1               Hamburg
2                Bayern
3   Nordrhein-Westfalen
4                Hessen
..                  ...
75        Niedersachsen
76  Nordrhein-Westfalen
77  Nordrhein-Westfalen
78        Niedersachsen
79  Nordrhein-Westfalen

[80 rows x 17 columns]

Baue Rankingtable

Get Area Ids

In [41]:
from OSMPythonTools.nominatim import Nominatim
nominatim = Nominatim()

def getAreaID(Stadt):
    return nominatim.query(f'{Stadt}, Germany').areaId()

Get Number of Schools, Trees

In [42]:
from OSMPythonTools.overpass import overpassQueryBuilder, Overpass
overpass = Overpass()

def getNofObjects(area, selector='"amenity"="school"'):
    # object can be 
    # "amenity"="school"'
    # "natural"="tree"
    query = overpassQueryBuilder(area=int(area), elementType='node', selector=selector, out='count')
    result = overpass.query(query)
    return result.countElements()


def getNofSchools(area):
    # print(area)
    return getNofObjects(area, selector='"amenity"="school"')

def getNofTrees(area):
    return getNofObjects(area, selector='"natural"="tree"')

In [43]:
import math

townsTable.loc[:,('Name','areaID')]=math.nan
townsTable.loc[:,('Name','NoOfSchools')]=math.nan
townsTable.loc[:,('Name','NoOfTrees')]=math.nan

In [44]:
for myrow in range(len(townsTable)):
    print(townsTable.loc[myrow,('Name','Name')])
    if not math.isnan(townsTable.loc[myrow,('Name','areaID')]): continue
    
    townsTable.loc[myrow,('Name','areaID')] = getAreaID(townsTable.loc[myrow,('Name','Name')])

Berlin
Hamburg
München
Köln
Frankfurt am Main
Stuttgart
Düsseldorf
Leipzig
Dortmund
Essen
Bremen
Dresden
Hannover
Nürnberg
Duisburg
Bochum
Wuppertal
Bielefeld
Bonn
Münster
Mannheim
Karlsruhe
Augsburg
Wiesbaden
Mönchen­gladbach
Gelsenkirchen
Aachen
Braunschweig
Kiel
Chemnitz
Halle (Saale)
Magdeburg
Freiburg im Breisgau
Krefeld
Mainz
Lübeck
Erfurt
Oberhausen
Rostock
Kassel
Hagen
Potsdam
Saarbrücken
Hamm
Ludwigshafen am Rhein
Mülheim an der Ruhr
Oldenburg
Osnabrück
Leverkusen
Solingen
Darmstadt
Heidelberg
Herne
Neuss
Regensburg
Paderborn
Ingolstadt
Offenbach am Main
Fürth
Würzburg
Heilbronn
Ulm
Pforzheim
Wolfsburg
Bottrop
Göttingen
Reutlingen
Bremer­haven
Koblenz
Erlangen
Bergisch Gladbach
Remscheid
Jena
Recklinghausen
Trier
Salzgitter
Moers
Siegen
Hildesheim
Gütersloh

In [45]:
for myrow in range(len(townsTable)):
    print(townsTable.loc[myrow,('Name','Name')])
    if not math.isnan(townsTable.loc[myrow,('Name','NoOfSchools')]): continue
    
    townsTable.loc[myrow,('Name','NoOfSchools')] = getNofSchools(townsTable.loc[myrow,('Name','areaID')])

Berlin
Hamburg
München
Köln
Frankfurt am Main
Stuttgart
Düsseldorf
Leipzig
Dortmund
Essen
Bremen
Dresden
Hannover
Nürnberg
Duisburg
Bochum
Wuppertal
Bielefeld
Bonn
Münster
Mannheim
Karlsruhe
Augsburg
Wiesbaden
Mönchen­gladbach
Gelsenkirchen
Aachen
Braunschweig
Kiel
Chemnitz
Halle (Saale)
Magdeburg
Freiburg im Breisgau
Krefeld
Mainz
Lübeck
Erfurt
Oberhausen
Rostock
Kassel
Hagen
Potsdam
Saarbrücken
Hamm
Ludwigshafen am Rhein
Mülheim an der Ruhr
Oldenburg
Osnabrück
Leverkusen
Solingen
Darmstadt
Heidelberg
Herne
Neuss
Regensburg
Paderborn
Ingolstadt
Offenbach am Main
Fürth
Würzburg
Heilbronn
Ulm
Pforzheim
Wolfsburg
Bottrop
Göttingen
Reutlingen
Bremer­haven
Koblenz
Erlangen
Bergisch Gladbach
Remscheid
Jena
Recklinghausen
Trier
Salzgitter
Moers
Siegen
Hildesheim
Gütersloh

In [46]:
for myrow in range(len(townsTable)):
    print(townsTable.loc[myrow,('Name','Name')])
    if not math.isnan(townsTable.loc[myrow,('Name','NoOfTrees')]): continue
    
    townsTable.loc[myrow,('Name','NoOfTrees')] = getNofTrees(townsTable.loc[myrow,('Name','areaID')])

Berlin
Hamburg
München
Köln
Frankfurt am Main
Stuttgart
Düsseldorf
Leipzig
Dortmund
Essen
Bremen
Dresden
Hannover
Nürnberg
Duisburg
Bochum
Wuppertal
Bielefeld
Bonn
Münster
Mannheim
Karlsruhe
Augsburg
Wiesbaden
Mönchen­gladbach
Gelsenkirchen
Aachen
Braunschweig
Kiel
Chemnitz
Halle (Saale)
Magdeburg
Freiburg im Breisgau
Krefeld
Mainz
Lübeck
Erfurt
Oberhausen
Rostock
Kassel
Hagen
Potsdam
Saarbrücken
Hamm
Ludwigshafen am Rhein
Mülheim an der Ruhr
Oldenburg
Osnabrück
Leverkusen
Solingen
Darmstadt
Heidelberg
Herne
Neuss
Regensburg
Paderborn
Ingolstadt
Offenbach am Main
Fürth
Würzburg
Heilbronn
Ulm
Pforzheim
Wolfsburg
Bottrop
Göttingen
Reutlingen
Bremer­haven
Koblenz
Erlangen
Bergisch Gladbach
Remscheid
Jena
Recklinghausen
Trier
Salzgitter
Moers
Siegen
Hildesheim
Gütersloh

In [47]:
townsTable

   Rang(2020)               Name  \
   Rang(2020)               Name
0           1             Berlin
1           2            Hamburg
2           3            München
3           4               Köln
4           5  Frankfurt am Main
..        ...                ...
75         76        Salzgitter
76         77              Moers
77         78             Siegen
78         79         Hildesheim
79         80          Gütersloh

                                        Einwohnerzahl                    \
                                              1939[2]     1950     1960
0   .mw-parser-output .numericFormat-1000::after{c...  3336026  3274016
1                                             1698388  1605606  1836958
2                                              815212   831937  1101384
3                                              768352   594941   801142
4                                              548220   532037   675009
..                                                ...      ...      ...
75                                              45598   100667   108872
76                                              29646    34832    45908
77                                              37622    38787    48210
78                                              68679    72292    94352
79                                              32841    43111    52346

                                                                   \
       1970     1980     1990     2000     2010     2019     2020
0   3208719  3048759  3433695  3382169  3460725  3669491  3664088
1   1793640  1645095  1652363  1715392  1786448  1847253  1852478
2   1311978  1298941  1229026  1210223  1353186  1484226  1488202
3    849451   976694   953551   962884  1007119  1087863  1083498
4    666179   629375   644865   648550   679664   763380   764104
..      ...      ...      ...      ...      ...      ...      ...
75   119031   113600   114355   112302   102394   104291   103866
76    53410    99923   104595   107062   105506   103902   103487
77    57563   112320   109174   108476   103424   102770   101943
78    93373   102619   105291   103909   102794   101693   101055
79    75297    78221    86807    95156    96404   100861   100664

   Fläche in km² (2016) Ew./km² (2018)  \
   Fläche in km² (2016) Ew./km² (2018)
0                891.68           4088
1                755.22           2438
2                310.70           4736
3                405.02           2681
4                248.31           3033
..                  ...            ...
75               223.92            469
76                67.68           1533
77               114.69            897
78                92.18           1106
79               112.02            894

   Be­völ­ke­rungs-ent­wick­lung [%] (2020 ggü. 2019) Großstadt erst­mals1  \
   Be­völ­ke­rungs-ent­wick­lung [%] (2020 ggü. 2019) Großstadt erst­mals1
0                                               -0.15                 1747
1                                                0.28                 1787
2                                                0.27                 1852
3                                               -0.40                 1852
4                                                0.09                 1875
..                                                ...                  ...
75                                              -0.41                 1942
76                                              -0.40                 1975
77                                              -0.80                 1975
78                                              -0.63                 1974
79                                              -0.20                 2018

           Bun­des­land          Name
           Bun­des­land        areaID NoOfSchools NoOfTrees
0                Berlin  3.600062e+09       136.0  183279.0
1               Hamburg  3.600063e+09        68.0   66590.0
2                Bayern  3.600062e+09       157.0   29449.0
3   Nordrhein-Westfalen  3.600063e+09        62.0   17114.0
4                Hessen  3.600062e+09        31.0    6684.0
..                  ...           ...         ...       ...
75        Niedersachsen  3.600063e+09         6.0     855.0
76  Nordrhein-Westfalen  3.610068e+09         0.0    4696.0
77  Nordrhein-Westfalen  3.600163e+09         3.0     777.0
78        Niedersachsen  3.601177e+09        18.0    1280.0
79  Nordrhein-Westfalen  3.600138e+09         1.0    2548.0

[80 rows x 20 columns]

In [84]:
townsTable.columns

MultiIndex([(                                        'Rang(2020)', ...),
            (                                              'Name', ...),
            (                                     'Einwohnerzahl', ...),
            (                                     'Einwohnerzahl', ...),
            (                                     'Einwohnerzahl', ...),
            (                                     'Einwohnerzahl', ...),
            (                                     'Einwohnerzahl', ...),
            (                                     'Einwohnerzahl', ...),
            (                                     'Einwohnerzahl', ...),
            (                                     'Einwohnerzahl', ...),
            (                                     'Einwohnerzahl', ...),
            (                                     'Einwohnerzahl', ...),
            (                              'Fläche in km² (2016)', ...),
            (                                    'Ew./km² (2018)', ...),
            ('Be­völ­ke­rungs-ent­wick­lung [%] (2020 ggü. 2019)', ...),
            (                              'Großstadt erst­mals1', ...),
            (                                      'Bun­des­land', ...),
            (                                              'Name', ...),
            (                                              'Name', ...),
            (                                              'Name', ...)],
           )

In [111]:
townsTable_extract = townsTable[[('Name','Name'), ('Name','areaID'),('Name','NoOfSchools'),('Name','NoOfTrees'),('Einwohnerzahl','2020'),('Fläche in km² (2016)','Fläche in km² (2016)'),('Ew./km² (2018)','Ew./km² (2018)')]]
townsTable_extract

                 Name                                     Einwohnerzahl  \
                 Name        areaID NoOfSchools NoOfTrees          2020
0              Berlin  3.600062e+09       136.0  183279.0       3664088
1             Hamburg  3.600063e+09        68.0   66590.0       1852478
2             München  3.600062e+09       157.0   29449.0       1488202
3                Köln  3.600063e+09        62.0   17114.0       1083498
4   Frankfurt am Main  3.600062e+09        31.0    6684.0        764104
..                ...           ...         ...       ...           ...
75        Salzgitter   3.600063e+09         6.0     855.0        103866
76              Moers  3.610068e+09         0.0    4696.0        103487
77             Siegen  3.600163e+09         3.0     777.0        101943
78         Hildesheim  3.601177e+09        18.0    1280.0        101055
79          Gütersloh  3.600138e+09         1.0    2548.0        100664

   Fläche in km² (2016) Ew./km² (2018)
   Fläche in km² (2016) Ew./km² (2018)
0                891.68           4088
1                755.22           2438
2                310.70           4736
3                405.02           2681
4                248.31           3033
..                  ...            ...
75               223.92            469
76                67.68           1533
77               114.69            897
78                92.18           1106
79               112.02            894

[80 rows x 7 columns]

In [112]:
df = townsTable_extract
df.columns = [pair[1] for pair in df.columns]
df

,Name,areaID,NoOfSchools,NoOfTrees,2020,Fläche in km² (2016),Ew./km² (2018)
0,Berlin,3.600062e+09,136.0,183279.0,3664088,891.68,4088
1,Hamburg,3.600063e+09,68.0,66590.0,1852478,755.22,2438
2,München,3.600062e+09,157.0,29449.0,1488202,310.70,4736
3,Köln,3.600063e+09,62.0,17114.0,1083498,405.02,2681
4,Frankfurt am Main,3.600062e+09,31.0,6684.0,764104,248.31,3033
...,...,...,...,...,...,...,...
75,Salzgitter,3.600063e+09,6.0,855.0,103866,223.92,469
76,Moers,3.610068e+09,0.0,4696.0,103487,67.68,1533
77,Siegen,3.600163e+09,3.0,777.0,101943,114.69,897
78,Hildesheim,3.601177e+09,18.0,1280.0,101055,92.18,1106
79,Gütersloh,3.600138e+09,1.0,2548.0,100664,112.02,894

In [115]:
df.columns = ['Name','areaID',	'NoOfSchools',	'NoOfTrees',	'Population', 'Area', 'Population_density']
df

,Name,areaID,NoOfSchools,NoOfTrees,Population,Area,Population_density
0,Berlin,3.600062e+09,136.0,183279.0,3664088,891.68,4088
1,Hamburg,3.600063e+09,68.0,66590.0,1852478,755.22,2438
2,München,3.600062e+09,157.0,29449.0,1488202,310.70,4736
3,Köln,3.600063e+09,62.0,17114.0,1083498,405.02,2681
4,Frankfurt am Main,3.600062e+09,31.0,6684.0,764104,248.31,3033
...,...,...,...,...,...,...,...
75,Salzgitter,3.600063e+09,6.0,855.0,103866,223.92,469
76,Moers,3.610068e+09,0.0,4696.0,103487,67.68,1533
77,Siegen,3.600163e+09,3.0,777.0,101943,114.69,897
78,Hildesheim,3.601177e+09,18.0,1280.0,101055,92.18,1106
79,Gütersloh,3.600138e+09,1.0,2548.0,100664,112.02,894

In [119]:
for col in ['areaID',	'NoOfSchools',	'NoOfTrees',	'Population', 'Area', 'Population_density']:
    df[col] = df[col].astype('double')

/tmp/ipykernel_107879/1632494877.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype('double')

In [129]:
df['Trees_density'] = df.NoOfTrees/df.Area
df['Trees_per_person'] = df.NoOfTrees/df.Population
df['Persons_per_tree'] = df.Population / df.NoOfTrees

/tmp/ipykernel_107879/3418534651.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Trees_density'] = df.NoOfTrees/df.Area
/tmp/ipykernel_107879/3418534651.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Trees_per_person'] = df.NoOfTrees/df.Population
/tmp/ipykernel_107879/3418534651.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Persons_per_tree'] = df.Population / df.NoOfTrees

In [130]:
pd.set_option('display.max_rows', 500)
df.sort_values(by=['Trees_density'], ascending=False)

,Name,areaID,NoOfSchools,NoOfTrees,Population,Area,Population_density,Trees_density,Trees_per_person,Persons_per_tree
0,Berlin,3.600062e+09,136.0,183279.0,3664088.0,891.68,4088.0,205.543469,0.050020,19.991859
32,Freiburg im Breisgau,3.600063e+09,19.0,23321.0,230940.0,153.06,1504.0,152.365086,0.100983,9.902663
65,Göttingen,3.600191e+09,0.0,17798.0,116845.0,116.89,1025.0,152.262811,0.152321,6.565063
21,Karlsruhe,3.600063e+09,29.0,24039.0,308436.0,173.46,1805.0,138.585265,0.077938,12.830650
31,Magdeburg,3.600062e+09,23.0,26029.0,235775.0,201.00,1188.0,129.497512,0.110398,9.058166
39,Kassel,3.600063e+09,22.0,13453.0,201048.0,106.78,1888.0,125.988013,0.066914,14.944473
7,Leipzig,3.600063e+09,48.0,30796.0,597493.0,297.80,1974.0,103.411686,0.051542,19.401643
2,München,3.600062e+09,157.0,29449.0,1488202.0,310.70,4736.0,94.782749,0.019788,50.534891
1,Hamburg,3.600063e+09,68.0,66590.0,1852478.0,755.22,2438.0,88.172983,0.035946,27.819162
5,Stuttgart,3.602793e+09,31.0,17101.0,630305.0,207.35,3062.0,82.474078,0.027131,36.857786
73,Recklinghausen,3.600057e+09,3.0,4933.0,110705.0,66.50,1688.0,74.180451,0.044560,22.441719
8,Dortmund,3.601829e+09,16.0,20245.0,587696.0,280.71,2091.0,72.120694,0.034448,29.029192
76,Moers,3.610068e+09,0.0,4696.0,103487.0,67.68,1533.0,69.385343,0.045378,22.037266
12,Hannover,3.600059e+09,36.0,13738.0,534049.0,204.14,2636.0,67.296953,0.025724,38.873854
27,Braunschweig,3.600063e+09,7.0,12490.0,248561.0,192.18,1292.0,64.991154,0.050249,19.900801
53,Neuss,3.600163e+09,16.0,6361.0,153109.0,99.52,1545.0,63.916801,0.041546,24.069958
18,Bonn,3.600063e+09,18.0,8984.0,330579.0,141.06,2320.0,63.689210,0.027177,36.796416
9,Essen,3.600063e+09,26.0,13127.0,582415.0,210.34,2772.0,62.408482,0.022539,44.367715
15,Bochum,3.600063e+09,17.0,8892.0,364454.0,145.66,2503.0,61.046272,0.024398,40.986730
22,Augsburg,3.600062e+09,36.0,8872.0,295830.0,146.84,2010.0,60.419504,0.029990,33.344229
6,Düsseldorf,3.600063e+09,48.0,12295.0,620523.0,217.41,2849.0,56.552137,0.019814,50.469540
10,Bremen,3.600063e+09,34.0,18343.0,566573.0,325.56,1749.0,56.342917,0.032375,30.887696
30,Halle (Saale),3.600063e+09,16.0,7536.0,237865.0,135.02,1772.0,55.813953,0.031682,31.563827
11,Dresden,3.600192e+09,23.0,17028.0,556227.0,328.48,1689.0,51.838773,0.030613,32.665433
42,Saarbrücken,3.601187e+09,7.0,8566.0,179349.0,167.09,1082.0,51.265785,0.047762,20.937310
52,Herne,3.600062e+09,3.0,2546.0,156940.0,51.42,3041.0,49.513808,0.016223,61.641791
50,Darmstadt,3.600063e+09,20.0,5947.0,159174.0,122.09,1304.0,48.709968,0.037362,26.765428
17,Bielefeld,3.600063e+09,34.0,12543.0,333509.0,258.82,1290.0,48.462252,0.037609,26.589253
59,Würzburg,3.600062e+09,36.0,4000.0,126954.0,87.63,1459.0,45.646468,0.031507,31.738500
51,Heidelberg,3.600286e+09,9.0,4902.0,158741.0,108.84,1473.0,45.038589,0.030880,32.382905
41,Potsdam,3.600062e+09,8.0,8277.0,182112.0,188.61,944.0,43.884206,0.045450,22.002175
3,Köln,3.600063e+09,62.0,17114.0,1083498.0,405.02,2681.0,42.254703,0.015795,63.310623
46,Oldenburg,3.600062e+09,12.0,4282.0,169605.0,102.99,1633.0,41.576852,0.025247,39.608828
54,Regensburg,3.600062e+09,29.0,3337.0,152270.0,80.70,1891.0,41.350682,0.021915,45.630806
40,Hagen,3.601800e+09,2.0,6300.0,188687.0,160.45,1177.0,39.264568,0.033389,29.950317
20,Mannheim,3.600063e+09,57.0,5448.0,309721.0,144.96,2134.0,37.582781,0.017590,56.850404
34,Mainz,3.600063e+09,9.0,3506.0,217123.0,97.74,2221.0,35.870677,0.016148,61.928979
26,Aachen,3.600063e+09,9.0,5654.0,248878.0,160.85,1538.0,35.150762,0.022718,44.018040
36,Erfurt,3.600063e+09,15.0,9459.0,213692.0,269.88,792.0,35.048911,0.044265,22.591394
69,Erlangen,3.600062e+09,6.0,2427.0,112385.0,76.95,1455.0,31.539961,0.021595,46.306139
19,Münster,3.600063e+09,30.0,9017.0,316403.0,303.28,1036.0,29.731601,0.028498,35.089609
68,Koblenz,3.600063e+09,17.0,3082.0,113388.0,105.13,1085.0,29.316085,0.027181,36.790396
4,Frankfurt am Main,3.600062e+09,31.0,6684.0,764104.0,248.31,3033.0,26.917965,0.008748,114.318372
62,Pforzheim,3.600062e+09,13.0,2623.0,126016.0,98.00,1281.0,26.765306,0.020815,48.042699
71,Remscheid,3.600062e+09,7.0,1954.0,111516.0,74.52,1489.0,26.221149,0.017522,57.070624
28,Kiel,3.600027e+09,8.0,2805.0,246601.0,118.65,2086.0,23.640961,0.011375,87.914795
47,Osnabrück,3.600063e+09,36.0,2809.0,164223.0,119.80,1375.0,23.447412,0.017105,58.463154
79,Gütersloh,3.600138e+09,1.0,2548.0,100664.0,112.02,894.0,22.745938,0.025312,39.507064
72,Jena,3.600063e+09,10.0,2543.0,110731.0,114.76,971.0,22.159289,0.022966,43.543453
67,Bremer­haven,3.600063e+09,2.0,1870.0,113557.0,93.82,1211.0,19.931784,0.016468,60.725668
13,Nürnberg,3.600063e+09,28.0,3654.0,515543.0,186.38,2781.0,19.605108,0.007088,141.090038
58,Fürth,3.600062e+09,5.0,1226.0,128223.0,63.35,2017.0,19.352802,0.009561,104.586460
25,Gelsenkirchen,3.600063e+09,26.0,1960.0,259105.0,104.94,2484.0,18.677339,0.007565,132.196429
45,Mülheim an der Ruhr,3.600062e+09,11.0,1651.0,170921.0,91.28,1872.0,18.087204,0.009659,103.525742
16,Wuppertal,3.600062e+09,13.0,2984.0,355004.0,168.39,2105.0,17.720767,0.008406,118.969169
38,Rostock,3.600062e+09,25.0,3211.0,209061.0,181.26,1152.0,17.714885,0.015359,65.107755
43,Hamm,3.600062e+09,2.0,3676.0,178967.0,226.43,791.0,16.234598,0.020540,48.685256
35,Lübeck,3.600027e+09,56.0,3453.0,215846.0,214.21,1014.0,16.119696,0.015998,62.509702
61,Ulm,3.600062e+09,41.0,1909.0,126405.0,118.69,1064.0,16.083916,0.015102,66.215296
37,Oberhausen,3.600063e+09,8.0,1224.0,209566.0,77.09,2735.0,15.877546,0.005841,171.214052
29,Chemnitz,3.600063e+09,18.0,3308.0,244401.0,221.05,1118.0,14.964940,0.013535,73.881802
57,Offenbach am Main,3.600063e+09,4.0,655.0,130892.0,44.89,2868.0,14.591223,0.005004,199.835115
64,Bottrop,3.600063e+09,2.0,1418.0,117388.0,100.61,1167.0,14.094026,0.012080,82.784203
44,Ludwigshafen am Rhein,3.600062e+09,10.0,1081.0,172557.0,77.55,2206.0,13.939394,0.006265,159.627197
78,Hildesheim,3.601177e+09,18.0,1280.0,101055.0,92.18,1106.0,13.885875,0.012666,78.949219
74,Trier,3.600173e+09,9.0,1603.0,110674.0,117.13,945.0,13.685648,0.014484,69.041797
48,Leverkusen,3.600062e+09,18.0,984.0,163905.0,78.87,2077.0,12.476227,0.006003,166.570122
55,Paderborn,3.605611e+09,14.0,2177.0,151864.0,179.59,838.0,12.122056,0.014335,69.758383
23,Wiesbaden,3.600062e+09,21.0,2470.0,278609.0,203.93,1365.0,12.111999,0.008865,112.797166
33,Krefeld,3.600063e+09,23.0,1602.0,226844.0,137.77,1648.0,11.628076,0.007062,141.600499
60,Heilbronn,3.600063e+09,7.0,1075.0,126458.0,99.88,1261.0,10.762915,0.008501,117.635349
49,Solingen,3.600063e+09,12.0,937.0,159193.0,89.54,1780.0,10.464597,0.005886,169.896478
66,Reutlingen,3.602773e+09,9.0,871.0,116031.0,87.06,1332.0,10.004595,0.007507,133.215844
63,Wolfsburg,3.600062e+09,14.0,1852.0,123840.0,204.09,608.0,9.074428,0.014955,66.868251
14,Duisburg,3.600062e+09,32.0,2065.0,495885.0,232.80,2142.0,8.870275,0.004164,240.138015
56,Ingolstadt,3.600062e+09,10.0,1169.0,136952.0,133.37,1027.0,8.765090,0.008536,117.153122
24,Mönchen­gladbach,3.600062e+09,13.0,1443.0,259665.0,170.47,1534.0,8.464833,0.005557,179.948025
77,Siegen,3.600163e+09,3.0,777.0,101943.0,114.69,897.0,6.774784,0.007622,131.200772
70,Bergisch Gladbach,3.600173e+09,6.0,522.0,111636.0,83.09,1348.0,6.282344,0.004676,213.862069
75,Salzgitter,3.600063e+09,6.0,855.0,103866.0,223.92,469.0,3.818328,0.008232,121.480702

In [133]:
df.sort_values(by=['Persons_per_tree'], ascending=True)

,Name,areaID,NoOfSchools,NoOfTrees,Population,Area,Population_density,Trees_density,Trees_per_person,Persons_per_tree
65,Göttingen,3.600191e+09,0.0,17798.0,116845.0,116.89,1025.0,152.262811,0.152321,6.565063
31,Magdeburg,3.600062e+09,23.0,26029.0,235775.0,201.00,1188.0,129.497512,0.110398,9.058166
32,Freiburg im Breisgau,3.600063e+09,19.0,23321.0,230940.0,153.06,1504.0,152.365086,0.100983,9.902663
21,Karlsruhe,3.600063e+09,29.0,24039.0,308436.0,173.46,1805.0,138.585265,0.077938,12.830650
39,Kassel,3.600063e+09,22.0,13453.0,201048.0,106.78,1888.0,125.988013,0.066914,14.944473
7,Leipzig,3.600063e+09,48.0,30796.0,597493.0,297.80,1974.0,103.411686,0.051542,19.401643
27,Braunschweig,3.600063e+09,7.0,12490.0,248561.0,192.18,1292.0,64.991154,0.050249,19.900801
0,Berlin,3.600062e+09,136.0,183279.0,3664088.0,891.68,4088.0,205.543469,0.050020,19.991859
42,Saarbrücken,3.601187e+09,7.0,8566.0,179349.0,167.09,1082.0,51.265785,0.047762,20.937310
41,Potsdam,3.600062e+09,8.0,8277.0,182112.0,188.61,944.0,43.884206,0.045450,22.002175
76,Moers,3.610068e+09,0.0,4696.0,103487.0,67.68,1533.0,69.385343,0.045378,22.037266
73,Recklinghausen,3.600057e+09,3.0,4933.0,110705.0,66.50,1688.0,74.180451,0.044560,22.441719
36,Erfurt,3.600063e+09,15.0,9459.0,213692.0,269.88,792.0,35.048911,0.044265,22.591394
53,Neuss,3.600163e+09,16.0,6361.0,153109.0,99.52,1545.0,63.916801,0.041546,24.069958
17,Bielefeld,3.600063e+09,34.0,12543.0,333509.0,258.82,1290.0,48.462252,0.037609,26.589253
50,Darmstadt,3.600063e+09,20.0,5947.0,159174.0,122.09,1304.0,48.709968,0.037362,26.765428
1,Hamburg,3.600063e+09,68.0,66590.0,1852478.0,755.22,2438.0,88.172983,0.035946,27.819162
8,Dortmund,3.601829e+09,16.0,20245.0,587696.0,280.71,2091.0,72.120694,0.034448,29.029192
40,Hagen,3.601800e+09,2.0,6300.0,188687.0,160.45,1177.0,39.264568,0.033389,29.950317
10,Bremen,3.600063e+09,34.0,18343.0,566573.0,325.56,1749.0,56.342917,0.032375,30.887696
30,Halle (Saale),3.600063e+09,16.0,7536.0,237865.0,135.02,1772.0,55.813953,0.031682,31.563827
59,Würzburg,3.600062e+09,36.0,4000.0,126954.0,87.63,1459.0,45.646468,0.031507,31.738500
51,Heidelberg,3.600286e+09,9.0,4902.0,158741.0,108.84,1473.0,45.038589,0.030880,32.382905
11,Dresden,3.600192e+09,23.0,17028.0,556227.0,328.48,1689.0,51.838773,0.030613,32.665433
22,Augsburg,3.600062e+09,36.0,8872.0,295830.0,146.84,2010.0,60.419504,0.029990,33.344229
19,Münster,3.600063e+09,30.0,9017.0,316403.0,303.28,1036.0,29.731601,0.028498,35.089609
68,Koblenz,3.600063e+09,17.0,3082.0,113388.0,105.13,1085.0,29.316085,0.027181,36.790396
18,Bonn,3.600063e+09,18.0,8984.0,330579.0,141.06,2320.0,63.689210,0.027177,36.796416
5,Stuttgart,3.602793e+09,31.0,17101.0,630305.0,207.35,3062.0,82.474078,0.027131,36.857786
12,Hannover,3.600059e+09,36.0,13738.0,534049.0,204.14,2636.0,67.296953,0.025724,38.873854
79,Gütersloh,3.600138e+09,1.0,2548.0,100664.0,112.02,894.0,22.745938,0.025312,39.507064
46,Oldenburg,3.600062e+09,12.0,4282.0,169605.0,102.99,1633.0,41.576852,0.025247,39.608828
15,Bochum,3.600063e+09,17.0,8892.0,364454.0,145.66,2503.0,61.046272,0.024398,40.986730
72,Jena,3.600063e+09,10.0,2543.0,110731.0,114.76,971.0,22.159289,0.022966,43.543453
26,Aachen,3.600063e+09,9.0,5654.0,248878.0,160.85,1538.0,35.150762,0.022718,44.018040
9,Essen,3.600063e+09,26.0,13127.0,582415.0,210.34,2772.0,62.408482,0.022539,44.367715
54,Regensburg,3.600062e+09,29.0,3337.0,152270.0,80.70,1891.0,41.350682,0.021915,45.630806
69,Erlangen,3.600062e+09,6.0,2427.0,112385.0,76.95,1455.0,31.539961,0.021595,46.306139
62,Pforzheim,3.600062e+09,13.0,2623.0,126016.0,98.00,1281.0,26.765306,0.020815,48.042699
43,Hamm,3.600062e+09,2.0,3676.0,178967.0,226.43,791.0,16.234598,0.020540,48.685256
6,Düsseldorf,3.600063e+09,48.0,12295.0,620523.0,217.41,2849.0,56.552137,0.019814,50.469540
2,München,3.600062e+09,157.0,29449.0,1488202.0,310.70,4736.0,94.782749,0.019788,50.534891
20,Mannheim,3.600063e+09,57.0,5448.0,309721.0,144.96,2134.0,37.582781,0.017590,56.850404
71,Remscheid,3.600062e+09,7.0,1954.0,111516.0,74.52,1489.0,26.221149,0.017522,57.070624
47,Osnabrück,3.600063e+09,36.0,2809.0,164223.0,119.80,1375.0,23.447412,0.017105,58.463154
67,Bremer­haven,3.600063e+09,2.0,1870.0,113557.0,93.82,1211.0,19.931784,0.016468,60.725668
52,Herne,3.600062e+09,3.0,2546.0,156940.0,51.42,3041.0,49.513808,0.016223,61.641791
34,Mainz,3.600063e+09,9.0,3506.0,217123.0,97.74,2221.0,35.870677,0.016148,61.928979
35,Lübeck,3.600027e+09,56.0,3453.0,215846.0,214.21,1014.0,16.119696,0.015998,62.509702
3,Köln,3.600063e+09,62.0,17114.0,1083498.0,405.02,2681.0,42.254703,0.015795,63.310623
38,Rostock,3.600062e+09,25.0,3211.0,209061.0,181.26,1152.0,17.714885,0.015359,65.107755
61,Ulm,3.600062e+09,41.0,1909.0,126405.0,118.69,1064.0,16.083916,0.015102,66.215296
63,Wolfsburg,3.600062e+09,14.0,1852.0,123840.0,204.09,608.0,9.074428,0.014955,66.868251
74,Trier,3.600173e+09,9.0,1603.0,110674.0,117.13,945.0,13.685648,0.014484,69.041797
55,Paderborn,3.605611e+09,14.0,2177.0,151864.0,179.59,838.0,12.122056,0.014335,69.758383
29,Chemnitz,3.600063e+09,18.0,3308.0,244401.0,221.05,1118.0,14.964940,0.013535,73.881802
78,Hildesheim,3.601177e+09,18.0,1280.0,101055.0,92.18,1106.0,13.885875,0.012666,78.949219
64,Bottrop,3.600063e+09,2.0,1418.0,117388.0,100.61,1167.0,14.094026,0.012080,82.784203
28,Kiel,3.600027e+09,8.0,2805.0,246601.0,118.65,2086.0,23.640961,0.011375,87.914795
45,Mülheim an der Ruhr,3.600062e+09,11.0,1651.0,170921.0,91.28,1872.0,18.087204,0.009659,103.525742
58,Fürth,3.600062e+09,5.0,1226.0,128223.0,63.35,2017.0,19.352802,0.009561,104.586460
23,Wiesbaden,3.600062e+09,21.0,2470.0,278609.0,203.93,1365.0,12.111999,0.008865,112.797166
4,Frankfurt am Main,3.600062e+09,31.0,6684.0,764104.0,248.31,3033.0,26.917965,0.008748,114.318372
56,Ingolstadt,3.600062e+09,10.0,1169.0,136952.0,133.37,1027.0,8.765090,0.008536,117.153122
60,Heilbronn,3.600063e+09,7.0,1075.0,126458.0,99.88,1261.0,10.762915,0.008501,117.635349
16,Wuppertal,3.600062e+09,13.0,2984.0,355004.0,168.39,2105.0,17.720767,0.008406,118.969169
75,Salzgitter,3.600063e+09,6.0,855.0,103866.0,223.92,469.0,3.818328,0.008232,121.480702
77,Siegen,3.600163e+09,3.0,777.0,101943.0,114.69,897.0,6.774784,0.007622,131.200772
25,Gelsenkirchen,3.600063e+09,26.0,1960.0,259105.0,104.94,2484.0,18.677339,0.007565,132.196429
66,Reutlingen,3.602773e+09,9.0,871.0,116031.0,87.06,1332.0,10.004595,0.007507,133.215844
13,Nürnberg,3.600063e+09,28.0,3654.0,515543.0,186.38,2781.0,19.605108,0.007088,141.090038
33,Krefeld,3.600063e+09,23.0,1602.0,226844.0,137.77,1648.0,11.628076,0.007062,141.600499
44,Ludwigshafen am Rhein,3.600062e+09,10.0,1081.0,172557.0,77.55,2206.0,13.939394,0.006265,159.627197
48,Leverkusen,3.600062e+09,18.0,984.0,163905.0,78.87,2077.0,12.476227,0.006003,166.570122
49,Solingen,3.600063e+09,12.0,937.0,159193.0,89.54,1780.0,10.464597,0.005886,169.896478
37,Oberhausen,3.600063e+09,8.0,1224.0,209566.0,77.09,2735.0,15.877546,0.005841,171.214052
24,Mönchen­gladbach,3.600062e+09,13.0,1443.0,259665.0,170.47,1534.0,8.464833,0.005557,179.948025
57,Offenbach am Main,3.600063e+09,4.0,655.0,130892.0,44.89,2868.0,14.591223,0.005004,199.835115
70,Bergisch Gladbach,3.600173e+09,6.0,522.0,111636.0,83.09,1348.0,6.282344,0.004676,213.862069
14,Duisburg,3.600062e+09,32.0,2065.0,495885.0,232.80,2142.0,8.870275,0.004164,240.138015

80